apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brock-room-check
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brock-room-check
    spec:
      containers:
      - name: brock-room-check
        image: gcr.io/radical-sloth/brock-room-check
        ports:
        - containerPort: 80
