apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brock-room-check
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brock-room-check
    spec:
      containers:
      - name: brock-room-check
        image: gcr.io/radical-sloth/brock-room-check
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "25Mi"
            cpu: "50m"
